---
mode: required

method: netinstall-add

labels:
    step: "Display Manager"
    step[de]: "Display Manager"

default: SDDM

items:
    - id: SDDM
      name: sddm
      description: "QML-based display manager (KDE default)"
      screenshot: ""
      netinstall:
        name: "sddm"
        description: "SDDM display manager"
        selected: true
        critical: true
        immutable: false
        expanded: true
        hidden: false
        subgroups:
            - name: "SDDM"
              description: "SDDM packages"
              selected: true
              hidden: true
              packages:
                - sddm
                - sddm-openrc

    - id: LightDM
      name: lightdm
      description: "Cross-desktop display manager (GTK)"
      screenshot: ""
      netinstall:
        name: "lightdm"
        description: "LightDM display manager"
        selected: false
        critical: true
        immutable: false
        expanded: true
        hidden: false
        subgroups:
            - name: "LightDM"
              description: "LightDM packages"
              selected: true
              hidden: true
              packages:
                - lightdm
                - lightdm-openrc

    - id: LXDM
      name: lxdm
      description: "Lightweight display manager (LXDE)"
      screenshot: ""
      netinstall:
        name: "lxdm"
        description: "LXDM display manager"
        selected: false
        critical: true
        immutable: false
        expanded: true
        hidden: false
        subgroups:
            - name: "LXDM"
              description: "LXDM packages"
              selected: true
              hidden: true
              packages:
                - lxdm
                - lxdm-openrc

    - id: LY
      name: ly
      description: "Minimal TUI display manager"
      screenshot: ""
      netinstall:
        name: "ly"
        description: "LY display manager"
        selected: false
        critical: true
        immutable: false
        expanded: true
        hidden: false
        subgroups:
            - name: "LY"
              description: "LY packages"
              selected: true
              hidden: true
              packages:
                - ly
                - ly-openrc
