---
command: artix-service

services:
  - name: "acpid"
    action: "enable"
  - name: "bluetoothd"
    action: "enable"
  - name: "cronie"
    action: "enable"
  - name: "cupsd"
    action: "enable"
  - name: "dbus"
    action: "enable"
  - name: "dhcpcd"
    action: "enable"
  - name: "NetworkManager"
    action: "enable"
  - name: "power-profiles-daemon"
    action: "enable"
  - name: "sddm"
    action: "enable"
  - name: "syslog-ng"
    action: "enable"
  - name: "dinit-user-spawn"
    action: "enable"
